name: Build, Push, Pull, and Run Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: shahchhatru/routine-ms-django-graphql-server:latest

      - name: Post job cleanup
        if: always()
        run: docker logout

  # Job to pull and run the Docker image on the self-hosted server
  pull-and-run:
    runs-on: self-hosted
    name: Pull and Run Docker Image on Self-Hosted Server
    steps:
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: docker pull shahchhatru/routine-ms-django-graphql-server:latest

      - name: Stop and Remove Previous Container (if running)
        run: |
          docker stop routine-ms-container || true
          docker rm routine-ms-container || true

      - name: Run Docker Container with Host Networking
        run: |
          docker run -d \
          --network host \
          --name routine-ms-container \
          shahchhatru/routine-ms-django-graphql-server:latest

      - name: Verify Container is Running
        run: docker ps | grep routine-ms-container
